name: colab-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pillow
  - requests
  - numpy
  - pip
  - pip:
      - torch
      - transformers
      - fastapi
      - uvicorn[standard]
      - nest_asyncio
      - pyngrok

